version: '3.8'

services:
  shopapp:
    image: cdhai1901/ecommerce-api:1.0
    container_name: shopapp_container
    ports:
      - "8080:8080"
    environment:
      DB_HOST: sqlserver
      DB_PORT: 1433
      DB_USER: sa
      DB_PASSWORD: YourStrongPassword123
      DB_NAME: shopdb
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_container
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: YourStrongPassword123
    ports:
      - "1433:1433"
    volumes:
      - ./sql_data:/var/opt/mssql
