version: '3.8'

services:
  # =========================
  # SQL Server
  # =========================
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ecommerce-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Chuduchai@1901
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - ecommerce-net
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Chuduchai@1901' -Q 'SELECT 1'"]
      interval: 10s
      retries: 10
      timeout: 5s
      start_period: 20s

  # =========================
  # Init SQL Database
  # =========================
  sql-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./init.sql:/init.sql
    entrypoint: /bin/bash
    command: >
      -c "sleep 10 &&
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U SA -P 'Chuduchai@1901' -i /init.sql"
    networks:
      - ecommerce-net

  # =========================
  # Spring Boot App
  # =========================
  shopapp:
    build:
      context: .
      dockerfile: shopapp/Dockerfile
    container_name: ecommerce-shopapp
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - ecommerce-net

volumes:
  sql_data:

networks:
  ecommerce-net:
