# Build stage
FROM maven:3.9.3-eclipse-temurin-17 AS builder
WORKDIR /app

# Copy root pom + module domain + shopapp
COPY ../pom.xml ./
COPY ../domain ./domain
COPY . .

# Build jar (bao gồm domain)
RUN mvn clean package -DskipTests

# Run stage
FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
