spring.application.name=shopapp

spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=ecommerce;encrypt=false;trustServerCertificate=true
spring.datasource.username=chuduchai1901
spring.datasource.password=chuduchai1901
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate config
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect


# Server port
server.port=8080

secretKey=Y2h1ZHVjaGFpY2h1ZHVjaGFpY2h1ZHVjaGFpY2h1ZHVjaGFpY2h1ZHVjaGFpY2h1ZHVjaGFpY2h1ZHVjaGFp

app.api-prefix=/api